Fixes #12: added version
aicers/github-dashboard-server pull request #13
Opened 2022-07-14 02:56 UTC by soojlee0106

Added version with package

2022-07-14 04:37 UTC, msk commented
"Fixes #12"를 PR 제목에 적어주는 건 아무 효과가 없습니다. PR을 merge할 때 관련 이슈도 자동으로 close되게 하려면 "Fixes #12"를 본문에 적어주거나, 아니면 커밋할 때 커밋 메시지에 적어주어야 합니다. 제대로 되어 있는지 여부는 오른쪽 패널의 "Development" 섹션에 해당 이슈가 나와있는지를 보면 알 수 있습니다.

잘 된 예로 aicers/aice-web#209 를 보세요.  본문 설명 중에 `Close #...`이 있고, 해당 이슈가 오른쪽 Development 섹션에도 나와 있는 걸 볼 수 있습니다.

이 PR도 #12가 Development 섹션에 나오도록 고쳐주세요.

2022-07-14 04:44 UTC, soojlee0106 commented
Fixes #13 
Close Fixes #12

2022-07-14 04:59 UTC, msk requested changes
이 PR 대로면 `cargo build`시 실행파일이 두 개가 생깁니다. 기존의 `github-dashboard-server` 외에 `cargopkg`란 실행파일이 생기고, 후자가 `-V` 옵션을 처리하게 됩니다. #12의 의도는 옵션을 처리하는 별도 실행파일을 만드는 것이 아니고, 기존의 `github-dashboard-server`가 `-V` 옵션도 처리할 수 있게 만드는 겁니다. `cargopkg`는 없에고 `-V` 옵션을 `github-dashboard-server`에 추가해주세요.

2022-07-14 07:59 UTC, msk commented
#12 에서 이슈 설명이 부족한 부분이 있었습니다. 여기서 보충하면, `cargo run -- -V` 명령, 혹은 `target/debug/github-dashboard-server` 명령을 실행하ㅐㅆ을 때 프로그램 이름과 버전이 나오는 것은 맞습니다만, 보통 `-V` 옵션의 역할은 거기까지만입니다. 즉, 프로그램 이름과 버전을 출력하고 더 이상 다른 일은 안 하고 종료해야 합니다. 우리가 늘상 쓰고 있는 `cargo` 명령으로 시험해보세요. `cargo -V`라고 하면 버전 정보만 출력하고 그대로 종료합니다.

또 한 가지는, `-V` 옵션이 주어지지 않았을 때에는 이름과 버전 출력 없이 그대로 진행해야 한다는 점입니다. `cargo` 명령의 경우도 `cargo build` 처럼 `-V` 없이 실행하게 되면 버전 번호를 출력하지 않고 빌드를 진행합니다.

이 PR에서 고칠 점을 요약하면,

1. `-V` 옵션이 주어진 경우 프로그램 이름과 버전 번호만 출력 후 종료한다.
2. `-V` 옵션이 주어지지 않은 경우 정상적으로 프로그램을 수행(설정파일을 읽고 웹서버 구동 등)한다.

2022-07-15 07:04 UTC, soojlee0106 commented
Close #13

2022-07-15 21:20 UTC, msk requested changes

2022-07-15 21:20 UTC, msk commented on src/conf.rs
> +    if args.nth(1) == Some("-V".to_string()) {
함수는 한 가지 일만을 하도록 만드는 것이 좋습니다. `-V` 옵션을 처리하는 일은 `load_config`의 목적인 설정  파일을 읽어들이는 것에 부합하지 않으므로, 여기보다는 `main` 함수에서 `load_config`를 부르기 직전으로 옮기는 것이 좋겠습니다.

2022-07-15 21:20 UTC, msk commented on src/conf.rs
> +        exit(1);
`exit` 함수의 인자는 이 프로그램이 실행을 마칠 때 프로그램을 호출한 shell로 돌려주는 리턴값인데요, 0이면 정상 종료, 0이 아닌 값이면 에러가 발생했음을 의미합니다. 이 경우는 사용자가 `-V` 옵션을 명시했고, 프로그램도 그에 따른 결과를 출력하고 정상적으로 종료하는 것이므로 1이 아니라 0을 돌려주는 것이 적절합니다.

2022-07-18 02:27 UTC, msk approved these changes

2022-07-18 02:27 UTC, merged