Fix bug
aicers/github-dashboard-server pull request #24
Opened 2022-07-19 08:19 UTC by soojlee0106

Edit conf.rs file to fix bug

Fixes: #21

2022-07-19 08:32 UTC, msk requested changes

2022-07-19 08:32 UTC, msk commented on config.toml
> + [web]
이 파일은 사용자가 각자 자기 환경에 맞게 만들어 쓰는 파일입니다. 저장소에는 올리지 않는 것이 좋겠습니다.

2022-07-20 05:50 UTC, soojlee0106 commented
자동으로 웹서버 구동이 멈추는 현상을 없애기 위해 println!("{}", contents); 다음 줄에 exit(0);을 지우자 "mismatched types expected enum `Result<Config, anyhow::Error>` found unit type `()`"라고 문제가 뜹니다. Result<Config>와 Vec<String>이라는 types 사이에 충돌이 일어나고 있는 것 같은데 해결 방법을 찾지 못해 어려움을 겪고 있습니다.

2022-07-20 06:45 UTC, msk commented
> 자동으로 웹서버 구동이 멈추는 현상을 없애기 위해 println!("{}", contents); 다음 줄에 exit(0);을 지우자 "mismatched types expected enum `Result<Config, anyhow::Error>` found unit type `()`"라고 문제가 뜹니다. Result와 Vec이라는 types 사이에 충돌이 일어나고 있는 것 같은데 해결 방법을 찾지 못해 어려움을 겪고 있습니다.

`load_info` 함수의 마지막 statement가 `if`문이므로 `if`문 자체의 값은 타입이 함수 리턴 타입(`Result<Config>`)과 일치해야 합니다. `exit(0);`이 있을 때에는 해당 브랜치가 거기서 바로 종료하므로 타입이 관계가 없었지만, `exit(0);`을 없애고 나면 그 브랜치의 값이 `if`문의 값이 되므로 타입이 `Result<Config>`가 되어야 합니다. main 브랜치에 있는 것처럼 `contents`를 `toml::from_str`로 파싱해서 `Config`를 만들고, 브랜치가 `Ok(config)`로 끝나게 해 주면 될 겁니다.

2022-07-21 04:37 UTC, msk requested changes

2022-07-21 04:37 UTC, msk commented on src/conf.rs
> +                    println!("{}", contents);
설정 파일 내용을 출력할 필요는 없습니다. 디버깅하는 동안 임시로 넣은 코드가 포함되지 않았는지 검사하는 것도 git push 이전에 점검할 것 중 하나입니다.

2022-07-21 04:37 UTC, msk commented on src/conf.rs
> +            "-V" | "-version" => {
명령행 옵션은 short option과 long option이 있는데요, short option은 한 글자 짜리로 `-V` 처럼 `-`을 하나만 쓰고요, long option은 `--version`처럼 옵션 이름 전체를 다 써 주는데 `-`을 두 개 쓰는 것이 관례입니다.

2022-07-21 05:55 UTC, msk approved these changes

2022-07-21 05:55 UTC, merged