Add User_Agent Header
aicers/github-dashboard-server pull request #27
Opened 2022-07-22 06:20 UTC by kimhanbeom

- Fix send_github_query function,Config struct
- Add README.md contents(about token)
Resolves: #26

2022-07-22 19:20 UTC, msk requested changes

2022-07-22 19:20 UTC, msk commented on README.md
> +* `token` : Generated github access token value.(Token Generation : [github-access-token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-tok
보통 `(` 앞은 띄어 쓰고 `:` 앞에는 공백을 넣지 않습니다.

2022-07-22 19:20 UTC, msk commented on src/github.rs
> +    headers.insert(
[`bearer_auth`](https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.bearer_auth)를 쓰면 더 간단하게 가능합니다.

2022-07-25 00:24 UTC, kimhanbeom commented
변경 요청사항 수정 완료했습니다.

2022-07-25 03:24 UTC, msk approved these changes

2022-07-25 03:24 UTC, merged