Add key-value storage function
aicers/github-dashboard-server pull request #36
Opened 2022-07-29 05:52 UTC by kimhanbeom

- Add db functions (insert/delete/select)
- Modify config struct/README.md (about sled database)
- Modify query (get number/title)
Resolves: #29

2022-07-29 06:28 UTC, msk requested changes

2022-07-29 06:28 UTC, msk commented on README.md
> + tree_name = "db_tree_name"
Tree 이름은 사용자에게 노출되는 것이 아니므로 굳이 설정파일에서 지정할 필요가 없이 내부적으로 정해서 쓰는 게 좋겠습니다. 설정 항목이 늘어나면 사용자에게는 오히려 부담이니, 꼭 필요한 것들만 설정 가능하게 하고, 딱히 변경할 이유가 없는 것들은 프로그램 내부 상수로 유지하는 것이 좋습니다.

2022-07-29 06:28 UTC, msk commented on src/sled_database.rs
> +pub struct SledDatabase {
추상화 관점에서 볼 때, 내부 구현을 너무 노출하는 것은 좋지 않습니다.

DB의 경우 프로젝트의 요구 사항에 따라, 혹은 성능 문제 등에 의해 변경될 수도 있는 것이니, 가급적 내부 구현(이 경우는 sled)에 의존하는 부분은 인터페이스에 노출되지 않도록 해야 나중에 DB를 변경하더라도 프로그램의 다른 부분에 미치는 영향을 최소화할 수 있습니다. 그런 점에서 모듈 이름이나 struct 이름에 특정 crate 이름을 쓰는 것은 피하는 것이 좋겠습니다.

2022-07-29 06:40 UTC, kimhanbeom commented
해당 이슈들 수정 완료했습니다.

2022-07-31 16:00 UTC, msk approved these changes

2022-07-31 16:01 UTC, merged