Add owner name key
aicers/github-dashboard-server pull request #44
Opened 2022-08-02 05:47 UTC by BLYKIM

Close: #40

2022-08-02 05:57 UTC, msk requested changes

2022-08-02 05:57 UTC, msk commented on src/database.rs
>              .insert(&bincode::serialize(&key)?, bincode::serialize(&val)?)?;
`str`은 애초에 byte의 연속이므로 Tree에 저장하기 위해 굳이 `serialize`를 할 필요가 없습니다. (`val`은 추후 title 이외에 다른 정보(assignees 등)도 저장하게 되면 어차피 `serialize`가 필요하므로 굳이 지금 `serialize`를 없앨 필요는 없습니다. 하지만 `key`는 `serialize`가 불필요합니다.)

2022-08-02 06:16 UTC, msk requested changes

2022-08-02 06:16 UTC, msk commented on src/database.rs
> +    pub fn insert_issues(&self, resp: Vec<GitHubIssue>, conf: &Config) -> Result<()> {
함수간 coupling을 최소화하기 위해서는 공유하는 정보를 줄이는 것이 좋습니다. 이 경우 `insert_issues`가 필요한 것은 `owner`와 `name` 뿐이므로, `Config`를 다 인자로 주기보다는 해당하는 값 두 개만 주는 것이 바람직합니다. 그렇게하면 `Config`를 갖고 있지 않은 함수에서도 `insert_issues`를 호출할 수 있어 `insert_issues`의 범용성도 높여줍니다.

2022-08-02 06:18 UTC, BLYKIM commented on src/database.rs
> +    pub fn insert_issues(&self, resp: Vec<GitHubIssue>, conf: &Config) -> Result<()> {
인자로 넣으면서 고민하던 점이었는데 수정하겠습니다!

2022-08-02 06:31 UTC, msk commented
이걸 머지하면 `Database::select_all`가 제대로 동작을 안 하게 됩니다. `select_all`의 `key` 처리 부분도 고쳐야합니다.

2022-08-03 00:56 UTC, BLYKIM commented
key처리부분을 regex 정규표현식으로 parsing해서
owner/name#number =>

owner: String,
repo: String,
number: i32,
타입으로 각각 넣어주는걸로 수정했습니다.

2022-08-03 01:42 UTC, msk approved these changes

2022-08-03 02:01 UTC, merged