Set Cursor connection
aicers/github-dashboard-server pull request #48
Opened 2022-08-03 08:46 UTC by kimhanbeom

Resolves: #43

2022-08-03 09:24 UTC, kimhanbeom commented
@msk 
커서 구현 관련 궁금한 점이 있점서 comment를 남깁니다.
1.구현 사항 중 [커서로 위치를 기억]한다는 내용은  client측에서 issues(first:2)를 2번 호출할경우 각각 1,2번째/3,4번째의 issue값들을 리턴받을수 있게끔 기능구현이 되야되는건가요?

2022-08-04 02:42 UTC, msk requested changes

2022-08-04 02:42 UTC, msk commented on src/database.rs
> +    #[allow(unused)]
모든 이슈를 한꺼번에 다 읽어오는 것은 앞으로도 쓸 일이 없으니 지우는게 좋겠습니다.

2022-08-04 02:42 UTC, msk commented on src/database.rs
> +            let keystr: String = format!("{}/{}#{:03}", owner, name, item.number);
이건 왜 필요한가요? 순서대로 정렬하려고 그러신거면 나중에 GitHub에서 이슈 생성 시간 필드를 가져오고, 그 값을 기준으로 정렬하는게 나을 것 같습니다. 이 방식으로는 이슈 번호 자리수가 늘어나면 다시 고쳐줘야해서요.

2022-08-04 02:49 UTC, kimhanbeom commented on src/database.rs
> +            let keystr: String = format!("{}/{}#{:03}", owner, name, item.number);
현재 seld db는 key값으로 insert된 값들이 정렬되고 있습니다. 
예를 들어 
"aicer/server#1" / "aicer/server#3" / "aicer/server#14" / "aicer/server#26" / "aicer/server#34" 
순서로 insert  후 출력력 할 경우
"aicer/server#1" / "aicer/server#14" / "aicer/server#26" / "aicer/server#3" /"aicer/server#34"
와 같이 입력 순서와 맞지 않은 출력이 나와서 {:03} 을 format에 추가하였습니다.

2022-08-04 02:54 UTC, msk commented on src/database.rs
> +            let keystr: String = format!("{}/{}#{:03}", owner, name, item.number);
서버 쪽에서는 같은 프로젝트의 이슈들이 한데 모여있기만 하면, 그 안에서의 정렬 순서는 별 상관없을 것 같습니다. 어차피 클라이언트쪽에서는 가져간 이슈들을 사용자가 선택한 컬럼(number, title, assignee 등)에 따라서 다시 정렬할 거라서요.

2022-08-04 02:56 UTC, kimhanbeom commented on src/database.rs
> +            let keystr: String = format!("{}/{}#{:03}", owner, name, item.number);
@msk 
그럼 해당 부분 삭제 후 다시 commit 하겠습니다.

2022-08-04 02:59 UTC, kimhanbeom commented
변경 사항 수정 완료했습니다.

2022-08-04 04:14 UTC, msk requested changes

2022-08-04 04:14 UTC, msk commented on src/graphql.rs
> +        let db = match ctx.data::<Database>() {
[`query`](https://docs.rs/async-graphql/latest/async_graphql/types/connection/fn.query.html) 함수를 쓰면 인자의 에러 처리, 커서 디코딩 등을 자동으로 해 줍니다.

2022-08-04 04:14 UTC, msk commented on src/graphql.rs
> +        Some(after) => bincode::deserialize::<usize>(&base64::decode(after)?)? + 1,
커서를 몇 번째인지를 나타내는 값으로 쓰게 되면, 첫 번째 쿼리 처리 후 두번째 쿼리가 오기 전에 대량의 이슈가 추가된다든지 하면 전혀 엉뚱한 이슈들을 돌려주게 될 수 있습니다. 이런 문제를 방지하기 위해서 실제로 커서 위치의 이슈를 찾을 수 있는 값(이 프로젝트의 경우는 key값)을 커서로 사용합니다.

2022-08-04 04:14 UTC, msk commented on src/graphql.rs
> +        let val = base64::encode(bincode::serialize(&edge)?);
참고로 말하자면, 정수의 경우 base64로 인코딩하려고 굳이 bincode를 쓸 이유가 없습니다. [`to_be_bytes`](https://doc.rust-lang.org/std/primitive.usize.html#method.to_le_bytes) 같은 함수의 결과를 base64로 인코딩하는 것이 간단합니다.

2022-08-04 08:13 UTC, kimhanbeom commented
해당 사항 수정 완료 했습니다.

2022-08-05 01:14 UTC, msk approved these changes

2022-08-05 01:14 UTC, merged