Checkout remote codes
aicers/github-dashboard-server pull request #73
Opened 2022-08-24 04:41 UTC by kimhanbeom

Resolves: #66

2022-08-24 17:36 UTC, msk requested changes
private repo에서 소스 받아오려면 인증 과정이 필요할텐데 이 PR에는 없는 것 같습니다. aicers/piglet을 설정파일에 추가하고 테스트해보세요.

2022-08-25 04:25 UTC, kimhanbeom commented
config파일의 ssh를 이용한 private repo처리 추가 하였습니다.

2022-08-25 17:35 UTC, msk commented on src/checkout.rs
> +    if let Some(path) = dirs::cache_dir() {
이건 제가 이슈에 링크를 잘못 걸었습니다. [`BaseDir::cache_dir`](https://docs.rs/directories/latest/directories/struct.BaseDirs.html#method.cache_dir)이 아니라 [`ProjectDir::cache_dir`](https://docs.rs/directories/latest/directories/struct.ProjectDirs.html#method.cache_dir)를 써야합니다. 이슈에는 방금 고쳐 놓았습니다.

2022-08-25 17:41 UTC, msk commented on src/checkout.rs
> +            std::path::Path::new(&format!("{}{}", home_path, ssh)),
파일 경로는 `format!` 대신 [`Path::join`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.join)으로 합쳐주세요.

2022-08-25 17:43 UTC, msk commented on README.md
> +ssh = "/.ssh/id_ed25519"
경로가 `/`로 시작하면 보통 절대 경로를 의미합니다. 이건 상대 경로임을 분명히 하기 위해서 맨 앞의 `/`를 빼는 것이 좋겠습니다.

2022-08-26 00:02 UTC, kimhanbeom commented
해당 사항 수정 완료했습니다.

2022-08-26 00:29 UTC, msk approved these changes

2022-08-26 00:29 UTC, merged